### ISSUE TITLE
where is the csp.json?

### ISSUE THREAD

**Issue by chenbimo** [fastify/fastify-swagger-ui#8]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.7.0

### Plugin version

1.0.1

### Node.js version

14.x

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

10

### Description

when i upgrade @fastify/swagger from v7 to v8 and add @fastify/swagger-ui package,it tips csp.json is not found.

### Steps to Reproduce

```javascript
Error: Cannot find module './dist/csp.json'
Require stack:
- D:\codes\git\chensuiyi\yiapi\node_modules\.pnpm\@fastify+swagger-ui@1.0.1\node_modules\@fastify\swagger-ui\index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at fastifySwaggerUi (D:\codes\git\chensuiyi\yiapi\node_modules\.pnpm\@fastify+swagger-ui@1.0.1\node_modules\@fastify\swagger-ui\index.js:6:34)
    at Plugin.exec (D:\codes\git\chensuiyi\yiapi\node_modules\.pnpm\avvio@8.2.0\node_modules\avvio\plugin.js:130:19)
    at Boot.loadPlugin (D:\codes\git\chensuiyi\yiapi\node_modules\.pnpm\avvio@8.2.0\node_modules\avvio\plugin.js:272:10)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\codes\\git\\chensuiyi\\yiapi\\node_modules\\.pnpm\\@fastify+swagger-ui@1.0.1\\node_modules\\@fastify\\swagger-ui\\index.js'
  ]
}
```

**Comment by PoQuatre** [comment]
It seems that the `dist` directory was ignored by mistake.
https://github.com/fastify/fastify-swagger-ui/blob/a3ded7ab057995a9d85b05dc2855ae05a490c0a9/.gitignore#L90-L93

**Comment by chenbimo** [comment]
> It seems that the `dist` directory was ignored by mistake.
> 
> https://github.com/fastify/fastify-swagger-ui/blob/a3ded7ab057995a9d85b05dc2855ae05a490c0a9/.gitignore#L90-L93

Yes. I think you ar right.

**Comment by climba03003** [comment]
Would you like to send a PR to address the issue?

**Comment by mcollina** [comment]
Fixed in v1.0.2.
